import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "fedi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ul className="fedi">
          <Link style={{textDecoration:'none', fontSize: 'x-large' ,color: 'black'}} href="/"><li>Home</li></Link>
          <Link style={{textDecoration:'none', fontSize: 'x-large',color: 'black'}} href="/Users"><li>Users</li></Link>
          <Link style={{textDecoration:'none', fontSize: 'x-large',color: 'black'}} href="/Contact"><li>Contact</li></Link>
          <Link style={{textDecoration:'none', fontSize: 'x-large',color: 'black'}} href="/Apropos"><li>Apropos</li></Link>
        </ul>
        {children}
      </body>
    </html>
  );
}
